# Generated by Django 2.1 on 2018-08-24 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('creatDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('activation', models.BooleanField(default=True, verbose_name='是否激活')),
                ('type', models.CharField(choices=[('A', '管理员'), ('B', '普通用户')], default='B', max_length=1, verbose_name='类型')),
            ],
        ),
    ]
