# Generated by Django 2.1 on 2018-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('province', models.CharField(max_length=10, verbose_name='省份')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('openid', models.CharField(max_length=100, verbose_name='用户唯一标识')),
                ('session_key', models.CharField(max_length=100, verbose_name='会话密钥')),
            ],
        ),
    ]
